# Generated by Django 4.2.2 on 2023-06-15 10:59

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(blank=True, max_length=100, null=True)),
                ('username', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('chat_id', models.IntegerField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
                ('image', models.CharField(max_length=128, unique=True)),
                ('attempts', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('corrects', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='words', to='api.topic')),
            ],
        ),
        migrations.CreateModel(
            name='StudentWord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attempts', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('corrects', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='words', to='api.student')),
                ('word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.word')),
            ],
        ),
    ]
