# Generated by Django 4.2.2 on 2023-06-18 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_word_definition_wordimage_topicimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='word',
            name='image',
        ),
    ]
